---
title: "Data Analyses and Visualization Requests"
title-block-banner: "#DBDBDB"
format: 
    html:
        linkcolor:  "#086c35"
        toc: true
        toc-title: "Requests"
        theme: cosmo
        embed-resources: true
        smooth-scroll: true
mainfont: Lato
css: styles.css
extensions: 
    - request
---

Document last modified: {{< modified >}}

::: {.callout-note appearance="simple"}
The purpose of this document is to memorialize data analyses requests. The objective is to clarify the request and to maintain a log of who did what, when, and why.

To include a new request, follow this template using the shortcode `request` with positional arguments {TAG}{DATE}{SOURCE} {REQUESTED_BY} {SUMMARY} {RESOLUTION}. The {SUMMARY} and {RESOLUTION} arguments can handle lists[^1].
:::

[^1]: See initial request source code.

------------------------------------------------------------------------
{{< request 
"Projects on Fundable Lists serving small communities serving DACs"
"2025-09-10"
"Danielle"
"[Slack](https://enviropolicyinno.slack.com/archives/C08LXGF02AE/p1757529404074779)"
"Plot showing small communities expecting funding that are also DACs"
"[2025-09-10] Completed"
>}}

{{< request 
"Independent fed cap grant by categories: General, LSLR, EC"
"2025-09-09"
"Lauren"
"[Slack](https://enviropolicyinno.slack.com/archives/C08LXGF02AE/p1757445152789539?thread_ts=1757104941.967279&cid=C08LXGF02AE)"
"Overview plots that capture the individual year fed-cap-grant-amount-202X for each grant category."
"[2025-09-10] Completed"
>}}

{{< request 
"PF Carryover added to general carryover plot"
"2025-09-05"
"Lauren"
"[Slack](https://enviropolicyinno.slack.com/archives/C08LXGF02AE/p1757093964900689?thread_ts=1757024920.371109&cid=C08LXGF02AE)"
"Stack principal forgiveness carryover over general carryover across state fiscal year with bars colored by fed cap grant and direct labeling of principal forgiveness carryover"
"[2025-09-07] Completed"
>}}

{{< request 
"Overlaping lines viz in static plots"
"2025-08-07"
"Janet"
"[ROD](https://docs.google.com/document/d/1tXmqVYR7sLY_dD8xiqMMIIINsRmTzms0pA6Qq0ZeQjU/edit?tab=t.0#heading=h.cst0s9qykgpj)"
"Request originated from findings and recommendation documents, the solution was discussed and agreed upon by the group and consists of mapping factor to line type and provide a direct annotation."
"[2025-08-14] Completed"
>}}

{{< request 
"Plot breakdown by project type"
"2025-07-24"
"Danielle"
"[Slack](https://enviropolicyinno.slack.com/archives/C08LXGF02AE/p1753380722430609?thread_ts=1752680250.203129&cid=C08LXGF02AE)"
"Create a separate plots by type of projects to compare demand to available funds and expected funding for AL"
"[2025-07-24] Completed"
>}}

{{< request 
"Static plot"
"2025-07-16"
"Erica"
"[Slack](https://enviropolicyinno.slack.com/archives/C08LXGF02AE/p1752680250203129)"
"Static plot for project costs for lead service line projects New York SFY23-25"
"[2025-07-17] Completed"
>}}


{{< request 
"Additional columns"
"2025-07-14"
"Danielle"
"Slack DM"
"In the project type tab: 
{{PARA}} 
{{LIST}} 
{{LI}} Total_project_costs_DAC
{{LI}} Total_Funding_Amount_DAC
{{PARA}} 
In the small community tab:
{{PARA}} 
{{LIST}} 
{{LI}} Total_project_cost
{{LI}} Total_funding_amount
{{LI}} Total_project_cost_ef
{{LI}} Total_funding_amount_ef
{{LI}} Total_project_costs_DAC
{{LI}} Total_Funding_Amount_DAC
{{LI}} Total_project_costs_DAC_ef
{{LI}} Total_Funding_Amount_DAC_ef
"
"[2025-07-14] Completed"
>}}


{{< request 
"Lead and DAC viz" 
"2025-07-07" 
"[Slack](https://enviropolicyinno.slack.com/archives/C08LXGF02AE/p1751909873324029)" 
"Danielle" 
"Three additional columns to Project Dollars in Funding tracker State Data workseet and four new visualizations. 
{{PARA}} 
For state level data spreadsheet 
{{PARA}} 
{{LIST}} 
{{LI}} Total_funding_LSLI 
{{LI}} Total_funding_LSLR 
{{LI}} Total_project_costs_DAC 
{{PARA}} Following data viz: 
{{PARA}} 
{{LIST}} 
{{LI}} Total funding amounts LSLI yoy 
{{LI}} Total funding amounts LSLR yoy 
{{LI}} Total project costs for DACs (DAC demand yoy) 
{{LI}} Total DAC demand (aka project costs) vs. available funding "
"[2025-07-15] Completed: Applicable plots published for Alabama, Illinois, New York, Tennessee, and Texas.
{{PARA}}[2025-07-14] Plots forthcoming.
Included ***survey*** in the keyword search for lead service line inventory. Added the following columns: 
{{PARA}}
{{LIST}}
{{LI}}**funding_amount_lslr**
{{LI}}**funding_amount_lsli** 
{{LI}}**funding_amount_lslu**
{{LI}}**funding_amount_ef_lslr**
{{LI}}**funding_amount_ef_lsli**
{{LI}}**funding_amount_ef_lslu**
{{LI}}**project_cost_dac**
{{PARA}}[2025-07-11] Final changes approved. 
{{PARA}}[2025-07-10] Maria checked in with Janet regarding Lead designations. 
{{PARA}}[2025-07-09] Async conversations regarding adding the word survey for lead_type designation of lead lsli projects.
{{PARA}}[2025-07-08] Alignment call Danielle + Maria, viz for project costs instead of funding amounts.
{{PARA}}[2025-07-07] Initial request reviewed by Maria. Preliminary data summaries have been generated and initial visualizations have been created, but no changes have been pushed to the project dollars sheet or the by state viz sheet.
" 
>}}
